### ISSUE TITLE
Add infisical module

### ISSUE THREAD

**Issue by tafaust** [ehwplus/terraswarm#1]
# Open Source Secret Management

All-in-one platform to securely manage application configuration and secrets across your team and infrastructure.

Link: https://infisical.com/

---

How to test:

1. Initialize a Docker swarm with docker swarm init unless a Docker swarm is already running.
2. In main.tf, include the Terraswarm configuration (with the local path).
3. Execute `terraform init` && `terraform apply`.
4. Check if the Docker service deployed without errors. 🙂
5. Check if the Infisical service is usable according to their docs.

**Comment by tbcashy** [comment]
Feature added in https://github.com/ehwplus/terraswarm/issues/1
